parameters:
  - name:         checkout
    type:         stepList
    displayName:  Checkout steps
    default:      []
  - name:         presteps
    type:         stepList
    displayName:  Prepended steps
    default:      []
  - name:         poststeps
    type:         stepList
    displayName:  Appended steps
    default:      []
  - name:         enableConfigurationDebug
    type:         boolean
    displayName:  Enable Debug Configuration Jobs
    default:      'true'
  - name:         enableConfigurationDebugRidSpecific
    type:         boolean
    displayName:  Enable Debug RID-specifc Jobs
    default:      'false'
  - name:         enableConfigurationRelease
    type:         boolean
    displayName:  Enable Release Configuration Jobs
    default:      'true'
  - name:         enableRidAgnostic
    type:         boolean
    displayName:  Enable RID-agnostic Jobs
    default:      'true'
  - name:         enableRidWindows
    type:         boolean
    displayName:  Enable Windows RID Jobs
    default:      'true'
  - name:         enableRidLinux
    type:         boolean
    displayName:  Enable Linux RID Jobs
    default:      'true'
  - name:         enableRidMacOs
    type:         boolean
    displayName:  Enable macOS RID Jobs
    default:      'true'
  - name:         debugConfiguration
    type:         object
    displayName:  Debug Configuration Parameters
    default:      {}
  - name:         releaseConfiguration
    type:         object
    displayName:  Release Configuration Parameters
    default:      {}
  - name:         additionalConfigurations
    type:         object
    displayName:  Additional Configurations
    default:      []
  - name:         ridAgnostic
    type:         object
    displayName:  RID-Agnostic Parameters
  - name:         ridWindows
    type:         object
    displayName:  Windows RID Parameters
    default:      {}
  - name:         ridLinux
    type:         object
    displayName:  Linux RID Parameters
    default:      {}
  - name:         ridMacOs
    type:         object
    displayName:  macOS RID Parameters
    default:      {}
  - name:         additionalRuntimes
    type:         object
    displayName:  Additional RID Parameters
    default:      []
  - name:         common
    type:         object
    displayName:  Common Parameters
    default:
      arguments:
        - -p:BuildId=$(Build.BuildId) -p:BuildSourceBranch=$(Build.SourceBranch) -nodeReuse:false
  - name:         restore
    type:         object
    displayName:  Default Restore Parameters
    default:
      projects: |
        src/**/*.csproj
        tests?/**/*.csproj
        samples?/**/*.csproj
  - name:         build
    type:         object
    displayName:  Default Build Parameters
    default:
      projects: |
        src/**/*.csproj
        tests?/**/*.csproj
        samples?/**/*.csproj
  - name:         test
    type:         object
    displayName:  Default Test Parameters
    default:
      projects: |
        tests?/**/*.csproj
  - name:         pack
    type:         object
    displayName:  Default Pack Parameters
    default:      {}
  - name:         publish
    type:         object
    displayName:  Default Publish Parameters
    default:      {}
  - name:         augmentParameters
    type:         boolean
    displayName:  Augment Parameter Defaults
    default:      'true'

stages:
  - stage:        build
    displayName:  Build
    jobs:
      - ${{ if eq('true', parameters.augmentParameters) }}:
        - template: ../generic/jobs/invoke-lvl2-augment.yml
          parameters:
            invoke:
              template: ../../dotnetcore/azure-pipelines.yml
              parameters:
                augmentParameters: false
                ${{ each param in parameters }}:
                  ${{ if ne('augmentParameters', param.key) }}:
                    ${{ param.key }}: ${{ param.value }}
            operand:
              debugConfiguration:
                job:
                  sequenceAppend.job:
                    - Debug
                  sequenceAppend.displayName:
                    - Debug
                  sequenceAppend.variables:
                    - name:   BuildConfiguration
                      value:  Debug
                common:
                  sequenceAppend.displayName:
                    - --configuration Debug
                  sequenceAppend.arguments:
                    - --configuration Debug
                restore:
                  sequenceAppend.displayName: []
                  sequenceAppend.arguments:   []
            keys:
              - debugConfiguration:
                - job
                - common
                - restore
      - ${{ if ne('true', parameters.augmentParameters) }}:
        - template: intermediate-jobs/00-root.yml
          parameters:
            checkout:
              - ${{ each step in parameters.checkout }}:
                - ${{ step }}
            presteps:
              - ${{ each step in parameters.presteps }}:
                - ${{ step }}
            poststeps: ${{ parameters.poststeps }}
            configurations:
              - ${{ if and(eq('true', parameters.enableConfigurationDebug), ne(variables.null, parameters.debugConfiguration)) }}:
                - ${{ parameters.debugConfiguration }}
              - ${{ if and(eq('true', parameters.enableConfigurationRelease), ne(variables.null, parameters.releaseConfiguration)) }}:
                - ${{ parameters.releaseConfiguration }}
              - ${{ each conf in parameters.additionalConfigurations }}:
                - ${{ conf }}
            runtimes:
              - ${{ if and(eq('true', parameters.enableRidAgnostic), ne(variables.null, parameters.ridAgnostic)) }}:
                - ${{ parameters.ridAgnostic }}
              - ${{ if and(eq('true', parameters.enableRidWindows), ne(variables.null, parameters.ridWindows)) }}:
                - ${{ parameters.ridWindows }}
              - ${{ if and(eq('true', parameters.enableRidLinux), ne(variables.null, parameters.ridLinux)) }}:
                - ${{ parameters.ridLinux }}
              - ${{ if and(eq('true', parameters.enableRidMacOs), ne(variables.null, parameters.ridMacOs)) }}:
                - ${{ parameters.ridMacOs }}
              - ${{ each rid in parameters.additionalRuntimes }}:
                - ${{ rid }}
            common:   ${{ parameters.common }}
            job:      ${{ parameters.job }}
            restore:  ${{ parameters.restore }}
            build:    ${{ parameters.build }}
            test:     ${{ parameters.test }}
            pack:     ${{ parameters.pack }}
            publish:  ${{ parameters.publish }}
