version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    reviewers:
      - 'thnetii/organization'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    reviewers:
      - 'thnetii/organization'
  - package-ecosystem: gitsubmodule
    directory: /
    open-pull-requests-limit: 50
    schedule:
      interval: daily
    reviewers:
      - 'thnetii/organization'
