version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    reviewers:
      - fredrikhr
  - package-ecosystem: npm
    directory: "/src/azure-pipelines-vso-eslint"
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    reviewers:
      - fredrikhr
  - package-ecosystem: npm
    directory: "/src/azure-pipelines-vso-tsc"
    schedule:
      interval: daily
    open-pull-requests-limit: 50
    reviewers:
      - fredrikhr
