root: true
env:
  es2020: true
  node: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - eslint:recommended
  - plugin:node/recommended
  - airbnb-base
rules:
  no-restricted-syntax:
    - error
    # ref. https://github.com/airbnb/javascript/blob/64b965efe0355c8290996ff5a675cd8fb30bf843/packages/eslint-config-airbnb-base/rules/style.js#L334-L352
    # Remove airbnb-base rule that prevents ForOfStatement
    - selector: ForInStatement
      message: for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.
    # - selector: ForOfStatement
    #   message: iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.
    - selector: LabeledStatement
      message: Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.
    - selector: WithStatement
      message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.'
