name: $(Date:yyyy-MM-dd)-rev$(Rev:r)

resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii

jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
