name: $(Date:yyyy-MM-dd)-rev$(Rev:r)

resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii

jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    defaultPool:
      vmImage:        windows-2019
    configurations:
    - id:             debug
      displayName:    Debug
      argValue:       Debug
    - id:             release
      displayName:    Release
      argValue:       Release
    includeWithoutRuntime: true
    runtimes:
    - id:           win
      argValue:     win10-x64
      displayName:  Windows, 64-bit
      pool:
        vmImage:    windows-2019
    - id:           linux
      argValue:     linux-x64
      displayName:  Linux, 64-bit
      pool:
        vmImage:    ubuntu-16.04
    - id:           osx
      argValue:     osx.10.14-x64
      displayName:  macOS, 64-bit
      pool:
        vmImage:    macOS-10.14
