name: $(Date:yyyy-MM-dd)-rev$(Rev:r)

resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii

jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    defaultPool:
      vmImage:        windows-2019
    configurations:
    - configuration:  debug
      displayName:    Debug
      value:          Debug

    - configuration:  release
      displayName:    Release
      value:          Release
    runtimes:
    - runtime:      winx64
      value:        win10-x64
      displayName:  Windows, 64-bit
      pool:
        vmImage:    windows-2019
    - runtime:      linuxx64
      value:        linux-x64
      displayName:  Linux, 64-bit
      pool:
        vmImage:    ubuntu-16.04
    - runtime:      osxx64
      value:        osx.10.14-x64
      displayName:  macOS, 64-bit
      pool:
        vmImage:    macOS-10.14
