name: $(Date:yyyy-MM-dd)-rev$(Rev:r)

resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines

variables:
  - name: defaultPool
    value:
      vmImage: windows-2019

  - name: configurations
    value:
    - configuration:  debug
      displayName:    Debug
      value:          Debug

    - configuration:  release
      displayName:    Release
      value:          Release

  - name: runtimes
    value:
    - runtime:      win10-x64
      value:        win10-x64
      displayName:  Windows 10, 64-bit
      pool:
        vmImage:    windows-2019
    - runtime:      linux-x64
      value:        linux-x64
      displayName:  Linux, 64-bit
      pool:
        vmImage:    ubuntu-16.04
    - runtime:      osx-x64
      value:        osx.10.14-x64
      displayName:  macOS, 64-bit
      pool:
        vmImage:    macOS-10.14

jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    configurations: ${{ variables.configurations }}
    defaultPool:    ${{ variables.defaultPool }}
