name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/THNETII.AzureDevOps.Pipelines.GitHubTaskLibrary/*
    - templates/githubaccesstoken/*
pr: none
steps:
- checkout:   none
- task: thnetii.thnetii-azuredevops-pipelines-githubtasklibrary.githubaccesstokentask.githubaccesstokentask@0
  displayName: 'Get GitHub Access Token'
  inputs:
    gitHubConnection: thnetii
- pwsh: |
    [System.Net.ServicePointManager]::SecurityProtocol = `
      [System.Net.ServicePointManager]::SecurityProtocol -bor `
      [System.Net.SecurityProtocolType]::Tls12

    [securestring]$GitHubAccessToken = ConvertTo-SecureString $ENV:GitHubAccessToken -AsPlainText -Force
    $GitHubApiHeaders = @{
      Accept = "application/vnd.github.machine-man-preview+json"
    };

    [uri]$GitHubApiUri = "https://api.github.com/installation/repositories"
    try {
      $GitHubApiResponse = Invoke-RestMethod -Method Get -Uri $GitHubApiUri `
        -Authentication OAuth -Token $GitHubAccessToken `
        -Headers $GitHubApiHeaders `
        -SessionVariable GitHubApiSession `
        -ErrorVariable GitHubApiError
      $GitHubApiJson = $GitHubApiResponse | ConvertTo-Json
    } catch {
      $GitHubApiJson = $GitHubApiError[0].Message | ConvertFrom-Json | ConvertTo-Json
    }
    Write-Host $GitHubApiJson

    Write-Host

    [uri]$GitHubApiUri = "https://api.github.com/user/installations"
    try {
      $GitHubApiResponse = Invoke-RestMethod -Method Get -Uri $GitHubApiUri `
        -Authentication OAuth -Token $GitHubAccessToken `
        -Headers $GitHubApiHeaders `
        -WebSession $GitHubApiSession `
        -ErrorVariable GitHubApiError
      $GitHubApiJson = $GitHubApiResponse | ConvertTo-Json
    } catch {
      $GitHubApiJson = $GitHubApiError[0].Message | ConvertFrom-Json | ConvertTo-Json
    }
    Write-Host $GitHubApiJson

  env:
    GitHubAccessToken: $(GitHub.AccessToken)
