parameters:
  job:            {}
  defaultPool:    {}
  artifactPrefix: ''
  artifactFolder: ''
  configuration:  {}
  runtimes:       []
  common:         {}
  restore:        {}
  build:          {}
  test:           {}
  pack:           {}
  publish:        {}

jobs:
- ${{ each r in parameters.runtimes }}:
  - template: expand-common.yml
    parameters:
      runtime: ${{ r }}
      # artifactPrefix, artifactFolder
      ${{ if ne('', r.id) }}:
        # artifactPrefix
        ${{ if ne('', parameters.artifactPrefix) }}:
          artifactPrefix: ${{ parameters.artifactPrefix }}-${{ r.id }}
        ${{ if eq('', parameters.artifactPrefix) }}:
          artifactPrefix: ${{ r.id }}
        # artifactFolder
        ${{ if ne('', parameters.artifactFolder) }}:
          artifactFolder: ${{ parameters.artifactFolder }}/${{ r.id }}
        ${{ if eq('', parameters.artifactFolder) }}:
          artifactFolder: ${{ r.id }}
      common:
        ${{ if r.arguments }}:
          ${{ if parameters.common.arguments }}:
            arguments:  ${{ parameters.common.arguments }} ${{ r.arguments }}
          ${{ if not(parameters.common.arguments) }}:
            arguments:  ${{ r.arguments }}
        ${{ if not(r.arguments) }}:
          arguments:    ${{ parameters.common.arguments }}
        ${{ each pair in r.common }}:
          ${{ if notIn(pair.key, 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.common }}:
          ${{ if and(notIn(pair.key, r.common.*.key), notIn(pair.key, 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      restore:
        ${{ if ne('', r.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.restore.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.restore.displayNameSuffix }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.restore.displayNameSuffix) }}:
              displayNameSuffix: --runtime ${{ r.argValue }}
          # arguments
          ${{ if ne('', parameters.restore.arguments) }}:
            arguments: ${{ parameters.restore.arguments }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.restore.arguments) }}:
            arguments: --runtime ${{ r.argValue }}
        ${{ each pair in r.restore }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.restore }}:
          ${{ if and(notIn(pair.key, r.restore.*.key), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      build:
        ${{ if ne('', r.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.build.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.build.displayNameSuffix }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.build.displayNameSuffix) }}:
              displayNameSuffix: --runtime ${{ r.argValue }}
          # arguments
          ${{ if ne('', parameters.build.arguments) }}:
            arguments: ${{ parameters.build.arguments }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.build.arguments) }}:
            arguments: --runtime ${{ r.argValue }}
        ${{ each pair in r.build }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.build }}:
          ${{ if and(notIn(pair.key, r.build.*.key), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      test:
        ${{ if ne('', r.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.test.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.test.displayNameSuffix }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.test.displayNameSuffix) }}:
              displayNameSuffix: --runtime ${{ r.argValue }}
          # arguments
          ${{ if ne('', parameters.test.arguments) }}:
            arguments: ${{ parameters.test.arguments }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.test.arguments) }}:
            arguments: --runtime ${{ r.argValue }}
        ${{ each pair in r.test }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.test }}:
          ${{ if and(notIn(pair.key, r.test.*.key), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      pack:
        ${{ if ne('', r.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.pack.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.pack.displayNameSuffix }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.pack.displayNameSuffix) }}:
              displayNameSuffix: --runtime ${{ r.argValue }}
          # arguments
          ${{ if ne('', parameters.pack.arguments) }}:
            arguments: ${{ parameters.pack.arguments }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.pack.arguments) }}:
            arguments: --runtime ${{ r.argValue }}
        ${{ each pair in r.pack }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.pack }}:
          ${{ if and(notIn(pair.key, r.pack.*.key), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      publish:
        ${{ if ne('', r.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.publish.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.publish.displayNameSuffix }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.publish.displayNameSuffix) }}:
              displayNameSuffix: --runtime ${{ r.argValue }}
          # arguments
          ${{ if ne('', parameters.publish.arguments) }}:
            arguments: ${{ parameters.publish.arguments }} --runtime ${{ r.argValue }}
          ${{ if eq('', parameters.publish.arguments) }}:
            arguments: --runtime ${{ r.argValue }}
        ${{ each pair in r.publish }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.publish }}:
          ${{ if and(notIn(pair.key, r.publish.*.key), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      ${{ each pair in parameters }}:
        ${{ if notIn(pair.key, 'runtimes', 'runtime', 'artifactPrefix', 'artifactFolder', 'common', 'restore', 'build', 'test', 'pack', 'publish') }}:
          ${{ pair.key }}: ${{ pair.value }}
