parameters:
  configurations: []

jobs:
- ${{ each c in parameters.configurations }}:
  - template: each-runtime.yml
    parameters:
      configuration: ${{ c }}
      common:
        ${{ if c.arguments }}:
          ${{ if parameters.common.arguments }}:
            arguments:  ${{ parameters.common.arguments }} ${{ c.arguments }}
          ${{ if not(parameters.common.arguments) }}:
            arguments:  ${{ c.arguments }}
        ${{ if not(c.arguments) }}:
          arguments:    ${{ parameters.common.arguments }}
        ${{ each pair in c.common }}:
          ${{ if notIn(pair.key, 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.common }}:
          ${{ if and(not(containsValue(pair.key, c.common)), notIn(pair.key, 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      restore:
        ${{ each pair in c.restore }}:
          ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.restore }}:
          ${{ if not(containsValue(pair.key, c.restore)) }}:
            ${{ pair.key }}: ${{ pair.value }}
      build:
        ${{ if ne('', c.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.build.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.build.displayNameSuffix }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.build.displayNameSuffix) }}:
              displayNameSuffix: --configuration ${{ c.argValue }}
          # arguments
          ${{ if ne('', parameters.build.arguments) }}:
            arguments: ${{ parameters.build.arguments }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.build.arguments) }}:
            arguments: --configuration ${{ c.argValue }}
        ${{ if eq('', c.argValue) }}:
          displayNameSuffix:  ${{ parameters.build.displayNameSuffix }}
          arguments:          ${{ parameters.build.arguments }}
        ${{ each pair in c.build }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.build }}:
          ${{ if and(not(containsValue(pair.key, c.build)), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      test:
        ${{ if ne('', c.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.test.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.test.displayNameSuffix }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.test.displayNameSuffix) }}:
              displayNameSuffix: --configuration ${{ c.argValue }}
          # arguments
          ${{ if ne('', parameters.test.arguments) }}:
            arguments: ${{ parameters.test.arguments }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.test.arguments) }}:
            arguments: --configuration ${{ c.argValue }}
        ${{ if eq('', c.argValue) }}:
          displayNameSuffix:  ${{ parameters.test.displayNameSuffix }}
          arguments:          ${{ parameters.test.arguments }}
        ${{ each pair in c.test }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.test }}:
          ${{ if and(not(containsValue(pair.key, c.test)), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      pack:
        ${{ if ne('', c.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.pack.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.pack.displayNameSuffix }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.pack.displayNameSuffix) }}:
              displayNameSuffix: --configuration ${{ c.argValue }}
          # arguments
          ${{ if ne('', parameters.pack.arguments) }}:
            arguments: ${{ parameters.pack.arguments }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.pack.arguments) }}:
            arguments: --configuration ${{ c.argValue }}
        ${{ if eq('', c.argValue) }}:
          displayNameSuffix:  ${{ parameters.pack.displayNameSuffix }}
          arguments:          ${{ parameters.pack.arguments }}
        ${{ each pair in c.pack }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.pack }}:
          ${{ if and(not(containsValue(pair.key, c.pack)), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      publish:
        ${{ if ne('', c.argValue) }}:
          # displayNameSuffix
          ${{ if ne('', parameters.publish.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.publish.displayNameSuffix }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.publish.displayNameSuffix) }}:
              displayNameSuffix: --configuration ${{ c.argValue }}
          # arguments
          ${{ if ne('', parameters.publish.arguments) }}:
            arguments: ${{ parameters.publish.arguments }} --configuration ${{ c.argValue }}
          ${{ if eq('', parameters.publish.arguments) }}:
            arguments: --configuration ${{ c.argValue }}
        ${{ if eq('', c.argValue) }}:
          displayNameSuffix:  ${{ parameters.publish.displayNameSuffix }}
          arguments:          ${{ parameters.publish.arguments }}
        ${{ each pair in c.publish }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
        ${{ each pair in parameters.publish }}:
          ${{ if and(not(containsValue(pair.key, c.publish)), notIn(pair.key, 'displayNameSuffix', 'arguments')) }}:
            ${{ pair.key }}: ${{ pair.value }}
      ${{ each pair in parameters }}:
        ${{ if notIn(pair.key, 'configurations', 'configuration', 'common', 'restore', 'build', 'test', 'pack', 'publish') }}:
          ${{ pair.key }}: ${{ pair.value }}
