parameters:
  job:            {}
  artifactPrefix: ''
  artifactFolder: ''

jobs:
- job:          ${{ coalesce(parameters.job.id, 'default') }}
  condition:    ${{ parameters.job.condition }}
  displayName:  ${{ parameters.job.displayName }}
  ${{ if containsValue(parameters.job, 'pool') }}:
    pool:       ${{ parameters.job.pool }}
  ${{ if not(containsValue(parameters.job, 'pool')) }}:
    pool:       ${{ parameters.defaultPool }}
  steps:
  - template:   steps.yml
    parameters:
      pack:
        arguments: '--output "$(Build.ArtifactStagingDirectory)/nuget/${{ parameters.artifactFolder }}" ${{ parameters.pack.arguments }}'
        ${{ each pair in parameters.pack }}:
          ${{ if notIn(pair.key, 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
      publish:
        arguments: '--output "$(Build.ArtifactStagingDirectory)/artifacts/${{ parameters.artifactFolder }}" ${{ parameters.pack.arguments }}'
        ${{ each pair in parameters.pack }}:
          ${{ if notIn(pair.key, 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
      ${{ each pair in parameters }}:
        ${{ if notIn(pair.key, 'pack', 'publish') }}:
          ${{ pair.key }}: ${{ pair.value }}
