parameters:
  pool:
    vmImage: windows-2019
  configurationId:    debug
  configurationValue: debug
  configurationDisplayName: Debug
  runtimeId:
  runtimeValue:
  runtimeDisplayName:

jobs:
- template: jobs.yml
  parameters:
    pool: ${{ parameters.pool }}
    ${{ if eq(parameters.runtimeId, '') }}:
      jobId: ${{ parameters.configurationId }}
    ${{ if ne(parameters.runtimeId, '') }}:
      jobId: ${{ parameters.configurationId }}_${{ parameters.runtimeId }}
    ${{ if eq(parameters.runtimeDisplayName, '') }}:
      jobDisplayName: ${{ parameters.configurationDisplayName }}
    ${{ if ne(parameters.runtimeDisplayName, '') }}:
      jobDisplayName: ${{ parameters.configurationDisplayName }} (${{ parameters.runtimeDisplayName }})
    configurationId:    ${{ parameters.configurationId }}
    configurationValue: ${{ parameters.configurationValue }}
    runtimeId:          ${{ parameters.runtimeId }}
    runtimeValue:       ${{ parameters.runtimeValue }}
