parameters:
  configuration:
    id: default
    displayName:
    argValue:
  runtime:
    id: default
    displayName:
    argValue:
    pool:
      vmImage: windows-2019

jobs:
- template: job.yml
  parameters:
    job:
      ${{ if eq(parameters.runtime.id, '') }}:
        id: ${{ parameters.configuration.id }}
      ${{ if ne(parameters.runtime.id, '') }}:
        id: ${{ parameters.configuration.id }}_${{ parameters.runtime.id }}
      ${{ if eq(parameters.runtime.displayName, '') }}:
        displayName: ${{ parameters.configuration.displayName }}
      ${{ if ne(parameters.runtime.displayName, '') }}:
        displayName: ${{ parameters.configuration.displayName }} (${{ parameters.runtime.displayName }})
      pool: ${{ parameters.runtime.pool }}
    configuration:  ${{ parameters.configuration }}
    runtime:        ${{ parameters.runtime }}
