parameters:
  defaultPool:
    vmImage: windows-2019
  configuration:
    id: default
    displayName:
    argValue:
  includeWithoutRuntime: true
  runtimes:
  - id: default
    displayName:
    argValue:
    pool:
      vmImage: windows-2019

jobs:
- ${{ if parameters.includeWithoutRuntime }}:
  - template: per-agentPool.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      runtime:
        id:
        displayName:
        argValue:
        pool: ${{ parameters.defaultPool }}
- ${{ each r in parameters.runtimes }}:
  - template: per-agentPool.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      runtime: ${{ r }}

