parameters:
  job:            {}

jobs:
- template: job.yml
  parameters:
    job:
      # id
      ${{ if eq('', parameters.runtime.id) }}:
        ${{ if ne('', parameters.configuration.id) }}:
          id: ${{ parameters.configuration.id }}
        ${{ if eq('', parameters.configuration.id) }}:
          id: defaultJob
      ${{ if ne('', parameters.runtime.id ) }}:
        ${{ if ne('', parameters.configuration.id) }}:
          id: ${{ parameters.configuration.id }}_${{ parameters.runtime.id }}
        ${{ if eq('', parameters.configuration.id) }}:
          id: ${{ parameters.runtime.id }}

      # displayName
      ${{ if eq('', parameters.runtime.displayName) }}:
        displayName: ${{ parameters.configuration.displayName }}
      ${{ if ne('', parameters.runtime.displayName) }}:
        displayName: ${{ parameters.configuration.displayName }} (${{ parameters.runtime.displayName }})

      # condition
      ${{ if ne('', parameters.configuration.condition) }}:
        ${{ if ne('', parameters.runtime.condition) }}:
          condition: and(${{ parameters.configuration.condition }}, ${{ parameters.runtime.condition }})
        ${{ if eq('', parameters.runtime.condition) }}:
          condition: ${{ parameters.configuration.condition }}
      ${{ if eq('', parameters.configuration.condition) }}:
        ${{ if ne('', parameters.runtime.condition) }}:
          condition: ${{ parameters.runtime.condition }}

      # pool
      ${{ if parameters.runtime.pool }}:
        pool: ${{ parameters.runtime.pool }}
      ${{ if not(parameters.runtime.pool) }}:
        pool: ${{ parameters.defaultPool }}

      ${{ each pair in parameters.job }}:
        ${{ if notIn(pair.key, 'id', 'displayName', 'condition', 'pool') }}:
          ${{ pair.key }}: ${{ pair.value }}
    configuration:  ${{ parameters.configuration }}
    runtime:        ${{ parameters.runtime }}
    ${{ each pair in parameters }}:
      ${{ if notIn(pair.key, 'job', 'configuration', 'runtime') }}:
        ${{ pair.key }}: ${{ pair.value }}
