https://pkgs.dev.azure.com/thnetii/_packaging/azure-pipelines/nuget/v3/index.json
Authorization: Basic public kytcih33qnzu5xcibmbpetl5u7c3lgjharl2i5tv3xa3kgjvkooa

###
https://public:kytcih33qnzu5xcibmbpetl5u7c3lgjharl2i5tv3xa3kgjvkooa@pkgs.dev.azure.com/thnetii/_packaging/azure-pipelines/nuget/v3/index.json
