parameters:
- name:     checkout
  type:     stepList
  default:  []
- name:     presteps
  type:     stepList
  default:  []
- name:     poststeps
  type:     stepList
  default:  []

- name:     defaultPool
  type:     object
  default:  {}
  # vmImage:  windows-2019

- name:     job
  type:     object
  default:  {}
- name:     configuration
  type:     object
  default:  {}
  # id:           ''
  # displayName:  ''
  # condition:    ''
- name:     platforms
  type:     object
  default:  []
  # each entry:
  #   id:           ''
  #   argValue:     ''
  #   displayName:  ''
  #   condition:    ''
  #   pool:         null
  #   arguments:    ''
  #   common:       {} # common-like object
  #   restore:      {} # restore-like object
  #   build:        {} # build-like object
  #   test:         {} # test-like object
  #   pack:         {} # pack-like object
  #   publish:      {} # publish-like object

- name:     common
  type:     object
  default:  {}
  # allProjects:  ''
  # srcProjects:  ''
  # testProjects: ''
  # arguments:    ''

- name:     restore
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     build
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     test
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     pack
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     publish
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''

jobs:
- ${{ each p in parameters.platforms }}:
  - template: expand-common.yml
    parameters:
      platform: ${{ p }}
      common:
        # arguments: append p.arguments
        ${{ if p.arguments }}:
          ${{ if parameters.common.arguments }}:
            arguments:  ${{ parameters.common.arguments }} ${{ p.arguments }}
          ${{ if not(parameters.common.arguments) }}:
            arguments:  ${{ p.arguments }}
        ${{ if not(p.arguments) }}:
          arguments:    ${{ parameters.common.arguments }}

        ${{ if ne('', p.argValue) }}:
          platform:     ${{ p.argValue }}

        # forward rest of p.common
        ${{ each pair in p.common }}:
          ${{ if notIn(pair.key, 'arguments') }}:
            ${{ pair.key }}: ${{ pair.value }}

        # forward rest of the object
        ${{ each pair in parameters.common }}:
          ${{ if eq(variables.null, p.common[pair.key]) }}:
            ${{ if notIn(pair.key, 'arguments') }}:
              ${{ pair.key }}: ${{ pair.value }}
      restore:
        # (displayNameSuffix, arguments): append p.argValue
        ${{ if ne('', p.argValue) }}:
          platform:     ${{ p.argValue }}
          # displayNameSuffix
          ${{ if ne('', parameters.restore.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.restore.displayNameSuffix }} -p:Platform=${{ p.argValue }}
          ${{ if eq('', parameters.restore.displayNameSuffix) }}:
              displayNameSuffix: -p:Platform=${{ p.argValue }}
        ${{ if eq('', p.argValue) }}:
          displayNameSuffix:  ${{ parameters.restore.displayNameSuffix }}

        # forward p.restore
        ${{ each pair in p.restore }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
            ${{ pair.key }}: ${{ pair.value }}

        # forward rest of object
        ${{ each pair in parameters.restore }}:
          ${{ if eq(variables.null, p.restore[pair.key]) }}:
            ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
              ${{ pair.key }}: ${{ pair.value }}
      build:
        # (displayNameSuffix, arguments): append p.argValue
        ${{ if ne('', p.argValue) }}:
          platform:     ${{ p.argValue }}
          # displayNameSuffix
          ${{ if ne('', parameters.build.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.build.displayNameSuffix }} -p:Platform=${{ p.argValue }}
          ${{ if eq('', parameters.build.displayNameSuffix) }}:
              displayNameSuffix: -p:Platform=${{ p.argValue }}
        ${{ if eq('', p.argValue) }}:
          displayNameSuffix:  ${{ parameters.build.displayNameSuffix }}

        # forward p.build
        ${{ each pair in p.build }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
            ${{ pair.key }}: ${{ pair.value }}

        # forward rest of object
        ${{ each pair in parameters.build }}:
          ${{ if eq(variables.null, p.build[pair.key]) }}:
            ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
              ${{ pair.key }}: ${{ pair.value }}
      test:
        # (displayNameSuffix, arguments): append p.argValue
        ${{ if ne('', p.argValue) }}:
          platform:     ${{ p.argValue }}
          # displayNameSuffix
          ${{ if ne('', parameters.test.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.test.displayNameSuffix }} -p:Platform=${{ p.argValue }}
          ${{ if eq('', parameters.test.displayNameSuffix) }}:
              displayNameSuffix: -p:Platform=${{ p.argValue }}
        ${{ if eq('', p.argValue) }}:
          displayNameSuffix:  ${{ parameters.test.displayNameSuffix }}

        # forward p.test
        ${{ each pair in p.test }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
            ${{ pair.key }}: ${{ pair.value }}

        # forward rest of object
        ${{ each pair in parameters.test }}:
          ${{ if eq(variables.null, p.test[pair.key]) }}:
            ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
              ${{ pair.key }}: ${{ pair.value }}
      pack:
        # (displayNameSuffix, arguments): append p.argValue
        ${{ if ne('', p.argValue) }}:
          platform:     ${{ p.argValue }}
          # displayNameSuffix
          ${{ if ne('', parameters.pack.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.pack.displayNameSuffix }} -p:Platform=${{ p.argValue }}
          ${{ if eq('', parameters.pack.displayNameSuffix) }}:
              displayNameSuffix: -p:Platform=${{ p.argValue }}
        ${{ if eq('', p.argValue) }}:
          displayNameSuffix:  ${{ parameters.pack.displayNameSuffix }}

        # forward p.pack
        ${{ each pair in p.pack }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
            ${{ pair.key }}: ${{ pair.value }}

        # forward rest of object
        ${{ each pair in parameters.pack }}:
          ${{ if eq(variables.null, p.pack[pair.key]) }}:
            ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
              ${{ pair.key }}: ${{ pair.value }}
      publish:
        # (displayNameSuffix, arguments): append p.argValue
        ${{ if ne('', p.argValue) }}:
          platform:     ${{ p.argValue }}
          # displayNameSuffix
          ${{ if ne('', parameters.publish.displayNameSuffix) }}:
            displayNameSuffix: ${{ parameters.publish.displayNameSuffix }} -p:Platform=${{ p.argValue }}
          ${{ if eq('', parameters.publish.displayNameSuffix) }}:
              displayNameSuffix: -p:Platform=${{ p.argValue }}
        ${{ if eq('', p.argValue) }}:
          displayNameSuffix:  ${{ parameters.publish.displayNameSuffix }}

        # forward p.publish
        ${{ each pair in p.publish }}:
          ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
            ${{ pair.key }}: ${{ pair.value }}

        # forward rest of object
        ${{ each pair in parameters.publish }}:
          ${{ if eq(variables.null, p.publish[pair.key]) }}:
            ${{ if notIn(pair.key, 'displayNameSuffix', 'platform') }}:
              ${{ pair.key }}: ${{ pair.value }}
      ${{ each pair in parameters }}:
        ${{ if notIn(pair.key, 'platforms', 'platform', 'common', 'restore', 'build', 'test', 'pack', 'publish') }}:
          ${{ pair.key }}: ${{ pair.value }}
