parameters:
- name:     checkout
  type:     stepList
  default:  []
- name:     presteps
  type:     stepList
  default:  []
- name:     poststeps
  type:     stepList
  default:  []

- name:     defaultPool
  type:     object
  default:  {}
  # vmImage:  windows-2019

- name:     job
  type:     object
  default:  {}
  # id:           default
  # condition:    ''
  # displayName:  ''
  # pool:         null # defaultPool-like object
- name:     configuration
  type:     object
  default:  {}
  # id:     ''
- name:     platform
  type:     object
  default:  {}
  # id:     ''

- name:     restore
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     build
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     test
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     pack
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     publish
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''

jobs:
- job:          ${{ coalesce(parameters.job.id, 'default') }}MSBuild
  condition:    ${{ parameters.job.condition }}
  displayName:  ${{ parameters.job.displayName }}
  pool:         ${{ coalesce(parameters.job.pool, parameters.defaultPool) }}
  ${{ each pair in parameters.job }}:
    ${{ if notIn(pair.key, 'id', 'condition', 'displayName', 'pool', 'steps') }}:
      ${{ pair.key }}: ${{ pair.value }}
  steps:
  - template:   steps.yml
    parameters:
      ${{ if eq('', parameters.configuration.id) }}:
        ${{ if eq('', parameters.platform.id) }}:
          packArtifactName:     $(System.TeamProject)-msbuild-pack
          publishArtifactName:  $(System.TeamProject)-msbuild-artifacts
        ${{ if ne('', parameters.platform.id) }}:
          packArtifactName:     $(System.TeamProject)-msbuild-pack-${{ parameters.platform.id }}
          publishArtifactName:  $(System.TeamProject)-msbuild-artifacts-${{ parameters.platform.id }}
      ${{ if ne('', parameters.configuration.id) }}:
        ${{ if eq('', parameters.platform.id) }}:
          packArtifactName:     $(System.TeamProject)-msbuild-pack-${{ parameters.configuration.id }}
          publishArtifactName:  $(System.TeamProject)-msbuild-artifacts-${{ parameters.configuration.id }}
        ${{ if ne('', parameters.platform.id) }}:
          packArtifactName:     $(System.TeamProject)-msbuild-pack-${{ parameters.configuration.id }}-${{ parameters.platform.id }}
          publishArtifactName:  $(System.TeamProject)-msbuild-artifacts-${{ parameters.configuration.id }}-${{ parameters.platform.id }}
      ${{ each pair in parameters }}:
        ${{ if notIn(pair.key, 'packArtifactName', 'publishArtifactName', 'defaultPool', 'job', 'configuration', 'platform') }}:
          ${{ pair.key }}: ${{ pair.value }}
