parameters:
- name:     checkout
  type:     stepList
  default:  []
- name:     presteps
  type:     stepList
  default:  []
- name:     poststeps
  type:     stepList
  default:  []

- name:     defaultPool
  type:     object
  default:  {}
  # vmImage:  windows-2019

- name:     job
  type:     object
  default:  {}
- name:     configuration
  type:     object
  default:  {}
  # id:           ''
  # displayName:  ''
  # condition:    ''
- name:     platform
  type:     object
  default:  {}
  # id:           ''
  # displayName:  ''
  # condition:    ''
  # pool:         null # defaultPool-like

- name:     restore
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     build
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     test
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     pack
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''
- name:     publish
  type:     object
  default:  {}
  # skip:               true
  # displayNameSuffix:  ''
  # condition:          ''
  # projects:           ''
  # arguments:          ''

jobs:
- template: job.yml
  parameters:
    job:
      # id
      ${{ if eq('', parameters.platform.id) }}:
        id: ${{ coalesce(parameters.configuration.id, 'defaultJob') }}
      ${{ if ne('', parameters.platform.id ) }}:
        ${{ if ne('', parameters.configuration.id) }}:
          id: ${{ parameters.configuration.id }}_${{ parameters.platform.id }}
        ${{ if eq('', parameters.configuration.id) }}:
          id: ${{ parameters.platform.id }}

      # displayName
      ${{ if eq('', parameters.platform.displayName) }}:
        displayName: ${{ parameters.configuration.displayName }}
      ${{ if ne('', parameters.platform.displayName) }}:
        displayName: ${{ parameters.configuration.displayName }} (${{ parameters.platform.displayName }})

      # condition
      ${{ if ne('', parameters.configuration.condition) }}:
        ${{ if ne('', parameters.platform.condition) }}:
          condition: and(${{ parameters.configuration.condition }}, ${{ parameters.platform.condition }})
        ${{ if eq('', parameters.platform.condition) }}:
          condition: ${{ parameters.configuration.condition }}
      ${{ if eq('', parameters.configuration.condition) }}:
        ${{ if ne('', parameters.platform.condition) }}:
          condition: ${{ parameters.platform.condition }}

      # pool
      pool: ${{ coalesce(parameters.platform.pool, parameters.defaultPool) }}

      ${{ each pair in parameters.job }}:
        ${{ if notIn(pair.key, 'id', 'displayName', 'condition', 'pool') }}:
          ${{ pair.key }}: ${{ pair.value }}
    configuration:  ${{ parameters.configuration }}
    platform:       ${{ parameters.platform }}
    ${{ each pair in parameters }}:
      ${{ if notIn(pair.key, 'job', 'configuration', 'platform') }}:
        ${{ pair.key }}: ${{ pair.value }}
