parameters:
  - name:         checkout
    type:         stepList
    default:      []
  - name:         presteps
    type:         stepList
    displayName:  List of steps to execute before the steps of the job
    default:      []
  - name:         poststeps
    type:         stepList
    displayName:  List of steps to execute after the steps of the job
    default:      []
  - name:         job
    displayName:  The to run
    type:         job
  - name:         skip
    type:         boolean
    displayName:  Whether to skip the step and its pre- and post-steps.
    default:      'false'
jobs:
  - ${{ if ne('true', parameters.skip) }}:
    - ${{ each prop in parameters.job }}:
        ${{ if ne('steps', prop.key) }}:
          ${{ prop.key }}: ${{ prop.value }}
      steps:
        - ${{ each step in parameters.checkout }}:
          - ${{ step }}
        - ${{ each step in parameters.presteps }}:
          - ${{ step }}
        - ${{ each step in parameters.job.steps }}:
          - ${{ step }}
        - ${{ each step in parameters.poststeps }}:
          - ${{ step }}
