parameters:
  # defaultPool:                null

  # common:                     null
  #overrideCommon:              {}

  # configurations:             null
  disableConfigurationDebug:    false
  disableConfigurationRelease:  false
  #addConfigurations:           []

  # runtimes:                   null
  disableNoRuntime:             false
  disableWindowsRuntime:        false
  disableLinuxRuntime:          false
  disableMacOSRuntime:          false
  #addRuntimes:                 []

jobs:
- template: jobs/each-configuration.yml
  parameters:
    ${{ if not(parameters.defaultPool) }}:
      defaultPool:
        vmImage: windows-2019
    ${{ if not(parameters.common) }}:
      common:
        # allProjects
        ${{ if not(parameters.overrideCommon.allProjects) }}:
          allProjects:  '*.sln'
        # srcProjects
        ${{ if not(parameters.overrideCommon.srcProjects) }}:
          srcProjects:  '[Ss]rc/*/*.csproj'
        # testProjects
        ${{ if not(parameters.overrideCommon.testProjects) }}:
          testProjects: '[Tt]test/*/*.csproj'
        # arguments:
        ${{ if not(parameters.overrideCommon.arguments) }}:
          ${{ if parameters.overrideCommon.addArguments }}:
            arguments:    '-p:BuildId=$(Build.BuildId) $(AddCommonArguments) ${{ parameters.overrideCommon.addArguments }}'
          ${{ if not(parameters.overrideCommon.addArguments) }}:
            arguments:    '-p:BuildId=$(Build.BuildId) $(AddCommonArguments)'
        ${{ if parameters.overrideCommon.arguments }}:
          ${{ if parameters.overrideCommon.addArguments }}:
            arguments:    ${{ parameters.overrideCommon.arguments }} ${{ parameters.overrideCommon.addArguments }}
          ${{ if not(parameters.overrideCommon.addArguments) }}:
            arguments:    ${{ parameters.overrideCommon.arguments }}
        ${{ each pair in parameters.overrideCommon }}:
          ${{ if notIn(pair.key, 'arguments', 'addArguments') }}:
            ${{ pair.key }}: ${{ pair.value }}
    ${{ if not(parameters.configurations) }}:
      configurations:
      - ${{ if not(parameters.disableConfigurationDebug) }}:
        - id:             debug
          condition:      ne(variables['SkipConfigurationDebug'], 'true')
          displayName:    Debug
          argValue:       Debug
          arguments:      '$(AddDebugArguments)'
      - ${{ if not(parameters.disableConfigurationRelease) }}:
        - id:             release
          condition:      ne(variables['SkipConfigurationRelease'], 'true')
          displayName:    Release
          argValue:       Release
          arguments:      '$(AddReleaseArguments)'
      - ${{ each c in parameters.addConfigurations }}:
        - ${{ each pair in c }}:
            ${{ pair.key }}: ${{ pair.value }}
    ${{ if not(parameters.runtimes) }}:
      runtimes:
      - ${{ if not(parameters.disableNoRuntime) }}:
        - condition:    ne(variables['SkipNoRuntime'], 'true')
      - ${{ if not(parameters.disableWindowsRuntime) }}:
        - id:           win
          condition:    ne(variables['SkipWindowsRuntime'], 'true')
          argValue:     win10-x64
          displayName:  Windows, 64-bit
          pool:
            vmImage:    windows-2019
          pack:
            skip:       true
          arguments:    '$(AddWindowsArguments)'
      - ${{ if not(parameters.disableLinuxRuntime) }}:
        - id:           linux
          condition:    ne(variables['SkipLinuxRuntime'], 'true')
          argValue:     linux-x64
          displayName:  Linux, 64-bit
          pool:
            vmImage:    ubuntu-16.04
          pack:
            skip:       true
          arguments:    '$(AddLinuxArguments)'
      - ${{ if not(parameters.disableMacOSRuntime) }}:
        - id:           osx
          condition:    ne(variables['SkipMacOSRuntime'], 'true')
          argValue:     osx.10.14-x64
          displayName:  macOS, 64-bit
          pool:
            vmImage:    macOS-10.14
          pack:
            skip:       true
          arguments:    '$(AddMacOSArguments)'
      - ${{ each r in parameters.addRuntimes }}:
        - ${{ each pair in r }}:
            ${{ pair.key }}: ${{ pair.value }}
    ${{ each pair in parameters }}:
      ${{ pair.key }}: ${{ pair.value }}
