name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  branches:
    include:
      - master
      - rel/*
pr:
  - '*'
parameters:
  - name:         checkout
    type:         stepList
    displayName:  List of Checkout steps
    default:      []
  - name:         presteps
    type:         stepList
    displayName:  List of steps to execute before the steps of the job
    default:      []
  - name:         poststeps
    type:         stepList
    displayName:  List of steps to execute after the steps of the job
    default:      []
stages:
  - stage:        build
    displayName:  Build
    jobs:
      - template:   jobs/00-root.yml
        parameters:
          checkout:   ${{ parameters.checkout }}
          presteps:   ${{ parameters.presteps }}
          poststeps:  ${{ parameters.poststeps }}
          common:
            arguments:        -p:BuildId=$(Build.BuildId) -p:BuildSourceBranch=$(Build.SourceBranch) -logger:THNETII.AzureDevOps.Pipelines.MSBuild.AzureDevOpsLogger,"$(Build.SourcesDirectory)/bld/THNETII.AzureDevOps.Pipelines.MSBuild/lib/netcoreapp2.1/THNETII.AzureDevOps.Pipelines.MSBuild.dll" -nodeReuse:false
            allProjects:      '*.sln'
            buildProjects: |
              [Ss]rc/*/*.csproj
              [Ss]samples?/*/*.csproj
            testProjects:     '[Tt]ests?/*/*.csproj'
            publishProjects:  '[Ss]rc/*/*.csproj'
