name:     $(Date:yyyy-MM-dd)-rev$(Rev:r)

trigger:  none
pr:       none

pool:
  vmImage:      ubuntu-latest

steps:
  - template:   template.yml
    parameters:
      array:
        - value:  15
        - value:  42
        - value:  10
