name:     $(Date:yyyy-MM-dd)-rev$(Rev:r)

trigger:  none
pr:       none

pool:
  vmImage:      ubuntu-latest

parameters:
- name:     common
  type:     object
  default:
    arguments:  -p:TestProperty=Test
- name:     configurations
  type:     object
  default:
  - id:     debug
    common:
      arguments:  --configuration Debug
  - id:     release
    common:
      arguments:  --configuration Release

steps:
- ${{ each c in parameters.configurations }}:
  - template:   '../invoke/steps-merge-parameters.yml'
    parameters:
      source:       ${{ c }}
      targetTiers:  2
      target:
        invoke: parameters
      transforms:
        common:
          arguments:
            type:       'prepend'
            separator:  ' '
      invoke:
        template: '../playground/template.yml'
        parameters:
          presteps:
          - pwsh: 'Write-Host "This is the start of the template invocation for configruation ${{ c.id }}"'
          poststeps:
          - pwsh: 'Write-Host "This is the end of the template invocation for configruation ${{ c.id }}"'
          common: ${{ parameters.common }}


