name:     $(Date:yyyy-MM-dd)-rev$(Rev:r)

trigger:  none
pr:       none

pool:
  vmImage:      ubuntu-latest

jobs:
  - job: playground1
    strategy:
      matrix:
        configuration_debug:
          ConfigurationKey: debug
        configuration_release:
          ConfigurationKey: release
        runtime_default:
          RuntimeKey:       default
        runtime_windows:
          RuntimeKey:       windows
        runtime_linux:
          RuntimeKey:       linux
        runtime_macos:
          RuntimeKey:       macos
    variables:
      configuration_debug_displayName:    Debug
      configuration_release_displayName:  Release
    displayName:  $(ConfigurationKey)
    steps:
      - pwsh: |
          Write-Host "ConfigurationKey:`t$(ConfigurationKey)"
          Write-Host "RuntimeKey:`t$(RuntimeKey)"
        displayName: pwsh test $(ConfigurationKey) $(RuntimeKey)
