name:     $(Date:yyyy-MM-dd)-rev$(Rev:r)

trigger:  none
pr:       none

pool:
  vmImage:      ubuntu-latest

steps:
  - template:   ../generic/steps/invoke-merge.yml
    parameters:
      invoke:
        template:     ../../generic/steps/single.yml
        parameters:
          preItems:
            - staticPreItem1
            - staticPreItem2
          items:
            - staticItem1
            - staticItem2
