name:     $(Date:yyyy-MM-dd)-rev$(Rev:r)

trigger:  none
pr:       none

pool:
  vmImage:      ubuntu-latest

stages:
- stage: st1
  displayName: Preparations
  jobs:
  - job: gen
    displayName: Generate Build Steps
    steps:
    - template: ../vstssdk-loggingcommandfunctions/steps.yml
    - pwsh: |
        & ([System.IO.Path]::Combine(
          $ENV:Build_SourcesDirectory,
          "templates", "playground", "generate.ps1"
        ))
      name: steps
      displayName: Output steps for generated job
      env:
        LoggingCommandFunctions: $(PowerShell.LoggingCommandFunctions)
- stage: st2
  dependsOn: st1
  displayName: Jobs
  jobs:
  - job: exec
    displayName: Execute Generated Job
    steps:
    - $[ each step in stageDependencies.st1.outputs['gen.steps.items'] ]:
      - $[ step ]
