name:     $(Date:yyyy-MM-dd)-rev$(Rev:r)

trigger:  none
pr:       none

pool:
  vmImage:      ubuntu-latest

jobs:
  - job: generator
    displayName: Generate Job
    steps:
    - template: ../vstssdk-loggingcommandfunctions/steps.yml
    - pwsh: |
        & ([System.IO.Path]::Combine(
          $ENV:Build_SourcesDirectory,
          "templates", "playground", "generate.ps1"
        ))
      name: mtrx
      displayName: Generate Job Matrix
      env:
        LoggingCommandFunctions: $(PowerShell.LoggingCommandFunctions)
  - job: executor
    dependsOn: generator
    displayName: ''
    strategy:
      matrix: $[ dependencies.generator.outputs['mtrx.instances'] ]
    steps:
      - template: template.yml
