name:     $(Date:yyyy-MM-dd)-rev$(Rev:r)

trigger:  none
pr:       none

pool:
  vmImage:      ubuntu-latest

parameters:
  - name: preItems
    type: object
    default:
      - paramPreItem1
      - paramPreItem2
  - name: items
    type: object
    default:
      - paramItem1
      - paramItem2
  - name: nonExistStatic
    type: object
    default:
      append1:    nonExistStaticParamAppend1
      append2:    nonExistStaticParamAppend2
      replace1:   nonExistStaticParamReplace1
      replace2:   nonExistStaticParamReplace2

steps:
  - template:   ../generic/steps/invoke-merge.yml
    parameters:
      merge:      ${{ parameters }}
      sequences:
        items:
          operation:  append
        preItems:
          operation:  prepend
      mappings:
        nonExistStatic:
          prop1:
            operation:  append
          prop2:
            operation:  append
            separator:  ' '
            prefix:     Prefix
            suffix:     Suffix
      invoke:
        template:     ../../playground/template.yml
        parameters:
          preItems:
            - staticPreItem1
            - staticPreItem2
          items:
            - staticItem1
            - staticItem2
