version: 1
update_configs:
- package_manager: "dotnet:nuget"
  directory: /
  update_schedule: live
  default_assignees:
  - couven92
  automerged_updates:
  - match:
      dependency_type:  "production"
      update_type:      "semver:minor"
  - match:
      dependency_type:  "development"
      update_type:      "all"
- package_manager: "submodules"
  directory: /
  update_schedule: daily
  default_assignees:
  - couven92
  automerged_updates:
  - match:
      update_type: "all"
- package_manager: "javascript"
  directory: src/THNETII.AzureDevOps.Pipelines.GitHubTaskLibrary
  update_schedule: live
  default_assignees:
  - couven92
  automerged_updates:
  - match:
      update_type: "all"
- package_manager: "javascript"
  directory: src/THNETII.AzureDevOps.Pipelines.GitHubTaskLibrary/githubaccesstokentask
  update_schedule: live
  default_assignees:
  - couven92
  automerged_updates:
  - match:
      update_type: "all"
